# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a019655393b1e07baa3b1043a4a79570189b97cb5684aa72d64dc3d838d28fed0b9a53da12de13654eac8fb79f299223dc711527b64d303e48ff0ebb07ea85df

test:
  secret_key_base: 13a422853db0a337cd78cce064e2b42276bec13f4c5868a1ab287ce276bae4bcdd2c82ffe7e13d4b29903fe5ed184b035220453c927942f8b867d653f4729c51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
